### LAYOUT: one_monitor ###
# This file defines the single-monitor setup.

# Disable Left Monitor
monitor=DP-2,disable

# Enable Center Monitor (DP-3) and ensure it's at 0x0
monitor=DP-3,3440x1440@174.96,0x0,1#,bitdepth,10,cm,hdr

# Disable Right Monitor
monitor=DP-1,disable
