# See https://wiki.hyprland.org/Configuring/Variables/ for more
general {
    gaps_in = 5
    gaps_out = 20
    border_size = 2
    # col.active_border = rgba(6464ff4d) rgba(9696ff4d) 45deg
    col.active_border = rgba(ff64ff80) rgba(9696ffff) 45deg
    # col.active_border= rgba(00ccffff) rgba(33eeffff) 45deg
    col.inactive_border = rgba(6464ff4d)
    layout = dwindle
    resize_on_border = true
}
dwindle {
    smart_resizing = true
}
group {
    auto_group = true
     # col.border_active= rgba(33ccffee) rgba(00ff99ee) 45deg
    # col.border_active= rgba(ff00ffee) rgba(ff0099ee) 45deg
    col.border_active= rgba(ff64ff80) rgba(9696ffff) 45deg
    col.border_inactive= rgba(6464ff4d)
    groupbar {
        font_size= 16
        height=16
        text_offset=0
        col.active=rgba(ff64ff80)
        col.inactive=rgba(6464ff22)
        indicator_gap=-20
        indicator_height=24
        keep_upper_gap=false
        rounding=8

        round_only_edges=false
        gradient_round_only_edges=false
    }
}
