# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# JetBrains
# https://www.jetbrains.com/help/idea/2022.1/configuring-intellij-idea-for-linux.html#ws-intellij-idea-linux-window-rules
# windowrule = match:class ^(jetbrains-.*)$, float on
# windowrule = match:class ^(jetbrains-.*)$, match:float true, no_focus on

# Calculator rules
windowrule = match:class ^(org\.kde\.kcalc)$, float on
windowrule = match:class ^(org\.kde\.kcalc)$, size 400 600
windowrule = match:class ^(org\.kde\.kcalc)$, center on
# File explorer rules
# windowrule = match:class ^(org\.gnome\.Nautilus)$, float on
# windowrule = match:class ^(org\.gnome\.Nautilus)$, size 600 600
# windowrule = match:class ^(Thunar)$, float on
# windowrule = match:class ^(Thunar)$, size 600 600
# Browser file rules
# windowrule = match:class ^(xdg-desktop-portal-gtk)$, match:title ^(All Files)$, float on
# Btop rules
windowrule = match:class ^(kitty)$, match:title ^(btop)$, float on
windowrule = match:class ^(kitty)$, match:title ^(btop)$, size 1280 720
