# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=DP-2,2560x1440,-1440x-500,1,transform,1
monitor=DP-3,3440x1440@174.96,0x0,1#,bitdepth, 10, cm, hdr
monitor=DP-1,2560x1440,3440x-500,1,transform,1

# monitor=DP-2,disable
# monitor=DP-3,3440x1440@174.96,0x0,1,bitdepth,10
# monitor=DP-1,disable

# experimental {
#   xx_color_management_v4 = true
# }

