# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# JetBrains
# https://www.jetbrains.com/help/idea/2022.1/configuring-intellij-idea-for-linux.html#ws-intellij-idea-linux-window-rules
windowrule = float on, match:class (jetbrains-)(.*), match:title (.*)
windowrule = no_initial_focus on, match:class (jetbrains-)(.*), match:float 1

# Calculator rules
windowrule = float on, size 400 600, center on, match:class org.gnome.Calculator
# File explorer rules
windowrule = float on, size 600 600, match:class org.gnome.Nautilus
windowrule = float on, size 600 600, match:class Thunar
# Browser file rules
windowrule = float on, size 600 600, match:class xdg-desktop-portal-gtk, match:title ^All Files$
# Btop rules
windowrule = float on, size 1280 720, match:class kitty, match:title btop
