# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# --- Start of JetBrains ---
# https://www.jetbrains.com/help/idea/2022.1/configuring-intellij-idea-for-linux.html#ws-intellij-idea-linux-window-rules
windowrulev2 = float, class:(jetbrains-)(.*), title:(.*)
windowrulev2 = noinitialfocus, class:(jetbrains-)(.*), floating:1

