# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# JetBrains
# https://www.jetbrains.com/help/idea/2022.1/configuring-intellij-idea-for-linux.html#ws-intellij-idea-linux-window-rules
windowrule = float, class:(jetbrains-)(.*), title:(.*)
windowrule = noinitialfocus, class:(jetbrains-)(.*), floating:1

# Calculator rules
windowrule = float,class:org.gnome.Calculator
windowrule = size 400 600,class:org.gnome.Calculator
windowrule = center,class:org.gnome.Calculator
# File explorer rules
windowrule = float,class:org.gnome.Nautilus
windowrule = size 600 600,class:org.gnome.Nautilus
windowrule = float,class:Thunar
windowrule = size 600 600,class:Thunar
# Browser file rules
windowrule = float,class:xdg-desktop-portal-gtk,title:^All Files$
windowrule = size 600 600,class:xdg-desktop-portal-gtk,title:^All Files$
# Btop rules
windowrule = float,class:kitty,title:btop
windowrule = size 1280 720,class:kitty,title:btop
